name: ðŸ§ª LambdaTest Playwright Automation

on:
  push:
    branches: main
  workflow_dispatch: # allows manual trigger from GitHub UI

jobs:
  playwright-tests:
    name: Run Playwright Tests on LambdaTest
    runs-on: ubuntu-latest

    env:
      LT_USERNAME: ${{ secrets.LT_USERNAME }}
      LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
      BASE_URL: ${{secrets.BASE_URL}}

    steps:
      # âœ… Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # âœ… Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # âœ… Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # âœ… Step 4: Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # âœ… Step 5: Run tests on LambdaTest
      - name: Run Playwright Tests on LambdaTest
        run: |
          npx playwright test

      - name: Show Playwright report
        run: npx playwright show-report playwright-report


      # âœ… Step 6: Upload Playwright HTML report
      - name: Upload Playwright HTML Report
        if: always() # upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
